multi_color_dlo: false
num_of_nodes: 30

logging_level: "warn"

hsv_filter:
  # upper: [179, 55, 203]
  # lower: [0, 35, 130]
  upper: [179, 255 ,39]
  lower: [0, 0, 0]

trackdlo:
  # visibility_threshold (tau_vis): the max distance a node can be away from the current point cloud to be considered visible
  visibility_threshold: 0.008
  # dlo_pixel_width (w): the approximate dlo width when projected onto 2D
  dlo_pixel_width: 40
  # beta and lambda: MCT weights. the larger they are, the more rigid the object becomes
  beta: 0.35
  lambda: 50000
  # alpha: the alignment strength
  alpha: 3
  # mu: ranges from 0 to 1, large mu indicates the point cloud is noisy
  mu: 0.1
  # max_iter: the maximum number of iterations the EM loop undergoes before termination
  max_iter: 50
  # tol: EM optimization convergence tolerance
  tol: 0.0002
  # k_vis: the strength of visibility information's effect on membership probability computation
  k_vis: 50
  # d_vis: the max geodesic distance between two adjacent visible nodes for the nodes between them to be considered visible
  d_vis: 0.06
  # parameters for the GLTP registration during pre-processing
  beta_pre_proc: 3.0
  lambda_pre_proc: 1.0
  lle_weight: 10.0
  downsample_leaf_size: 0.008